storage:
  type: "SQLITE"
  
  table-prefix: "hbansystem_"

sqlite:
  file: "punishments.db"

mysql:
  host: "127.0.0.1"
  port: 3306
  database: "hbansystem"
  username: "root"
  password: ""
  use-ssl: false
  
  pool:
    maximum-pool-size: 10
    minimum-idle: 2
    connection-timeout: 10000
    idle-timeout: 600000
    max-lifetime: 1800000
